const livePairs=[['🇪🇺','EUR/USD','Euro / US Dollar','92%'],['🇬🇧','GBP/USD','British Pound / US Dollar','89%'],['🇯🇵','USD/JPY','US Dollar / Japanese Yen','88%'],['🇦🇺','AUD/USD','Australian / US Dollar','86%'],['🇨🇦','USD/CAD','US Dollar / Canadian Dollar','85%'],['🇬🇧','GBP/JPY','British Pound / Japanese Yen','83%']];
const otcPairs=[['🇪🇺','EUR/USD OTC','Euro / US Dollar','91%'],['🇬🇧','GBP/USD OTC','British Pound / US Dollar','88%'],['🇦🇺','AUD/CAD OTC','Australian / Canadian Dollar','87%'],['🇳🇿','NZD/USD OTC','New Zealand / US Dollar','84%'],['🇨🇭','USD/CHF OTC','US Dollar / Swiss Franc','82%'],['🇪🇺','EUR/JPY OTC','Euro / Japanese Yen','80%']];
let currentPairs=livePairs;
const titles={dashboard:['OVERVIEW','ড্যাশবোর্ড'],analyzer:['AI MARKET ENGINE','মার্কেট অ্যানালাইজার'],history:['ACTIVITY LOG','সিগন্যাল হিস্ট্রি'],plans:['MEMBERSHIP','সাবস্ক্রিপশন'],profile:['ACCOUNT','প্রোফাইল']};
function go(view){document.querySelectorAll('.view,.nav-item').forEach(e=>e.classList.remove('active'));document.getElementById(view)?.classList.add('active');document.querySelector(`.nav-item[data-view="${view}"]`)?.classList.add('active');document.getElementById('eyebrow').textContent=titles[view][0];document.getElementById('pageTitle').textContent=titles[view][1];document.getElementById('sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderMarket(type='live'){const rows=(type==='live'?livePairs:otcPairs).slice(0,4);document.getElementById('marketRows').innerHTML=rows.map((p,i)=>`<div class="market-row ${i===2?'down':''}"><div class="pair"><span class="flag">${p[0]}</span><div><b>${p[1]}</b><small>${p[2]}</small></div></div><div class="mini-chart"></div><div class="payout"><b>${p[3]}</b><small>PAYOUT</small></div></div>`).join('')}
function renderPairs(list=currentPairs){document.getElementById('pairGrid').innerHTML=list.map((p,i)=>`<button class="pair-card ${i===0?'selected':''}" data-pair="${p[1]}" data-flag="${p[0]}"><header><span><span class="flag-badge">${p[0]}</span><span class="pair-name"><strong>${p[1]}</strong><small>${p[2]}</small></span></span><span>${p[3]}</span></header><p><i></i> Market open <b>1M →</b></p></button>`).join('');document.querySelectorAll('.pair-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pair-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('selectedPair').textContent=b.dataset.pair;document.getElementById('selectedFlag').textContent=b.dataset.flag})}
document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-market]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMarket(b.dataset.market)});
document.querySelectorAll('[data-full-market]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-full-market]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentPairs=b.dataset.fullMarket==='live'?livePairs:otcPairs;renderPairs()});
document.getElementById('pairSearch').oninput=e=>renderPairs(currentPairs.filter(p=>p[1].toLowerCase().includes(e.target.value.toLowerCase())));
async function analyze(pair){const modal=document.getElementById('analysisModal');modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.getElementById('modalPair').textContent=pair;document.getElementById('modalText').textContent='মার্কেট ডেটা ও indicator confirmation যাচাই করা হচ্ছে…';document.querySelector('.loading').classList.remove('hidden');document.getElementById('retryBtn').classList.add('hidden');document.getElementById('resultDirection').classList.add('hidden');document.getElementById('resultMetrics').classList.add('hidden');try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pair,timeframe:'1m'})});if(!res.ok)throw new Error();const data=await res.json();document.getElementById('modalText').textContent='Multiple indicator confirmation complete';document.querySelector('.loading').classList.add('hidden');const d=document.getElementById('resultDirection');d.querySelector('b').textContent=data.direction;d.querySelector('em').textContent=`${data.confidence}%`;d.classList.remove('hidden');document.getElementById('resultMetrics').classList.remove('hidden')}catch{setTimeout(()=>{document.getElementById('modalText').textContent='এই মুহূর্তে বিশ্লেষণ সম্পন্ন হয়নি। কিছুক্ষণ পর আবার চেষ্টা করুন।';document.querySelector('.loading').classList.add('hidden');document.getElementById('retryBtn').classList.remove('hidden')},900)}}
document.getElementById('generateSelected').onclick=()=>analyze(document.getElementById('selectedPair').textContent);
document.getElementById('modalClose').onclick=()=>document.getElementById('analysisModal').classList.remove('show');document.getElementById('retryBtn').onclick=()=>analyze(document.getElementById('modalPair').textContent);document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('st-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('st-theme')==='light')document.body.classList.add('light');document.querySelectorAll('.plans-grid button,.profile-form button').forEach(b=>b.onclick=()=>{const t=document.getElementById('toast');t.textContent='আপনার অনুরোধ গ্রহণ করা হয়েছে';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)});renderMarket();renderPairs();
